# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd6e96ee4f195a684fb0d92347cbc29195afe3dcf1048f6c4be6ce825aa5e86438115241a9f3483ec593148e9e1f9836a3dea2d40ae6007427b3296d4bd7bdf4

test:
  secret_key_base: edd8f7d40b4304f9060abd35df7e82a6cf8de344b215cb2d12aa700a2a266d3589956729d2c358da935c85d51b8d70e1b43cb465cc372f8082f6e9806e9bc49c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
